# Folosim imaginea de baza
FROM php:8.1-apache

# Instalăm dependențele necesare și extensiile MySQL/MariaDB
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzip-dev \
    zip \
    unzip \
    mariadb-client \
    && docker-php-ext-install mysqli pdo pdo_mysql 

# Activați modul de rescriere Apache
RUN a2enmod rewrite